name: ASP.NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest


    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Install EF Tool
        run: |
            dotnet new tool-manifest
            dotnet tool install dotnet-ef
            dotnet add CityDiscoverTourist.API  package Microsoft.SqlServer.DacFx

      - name: dotnet publish
        run: dotnet publish CityDiscoverTourist.sln -c Release -o out 

      - uses: azure/actions/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/sql-action@v1
        with:
         server-name: city-discover-tourist.database.windows.net
         connection-string: ${{ secrets.CONNECTION_STRING }}
         dacpac-package: './CityDiscoverTourist.dacpac'
         arguments: '/p:DropObjectsNotInSource=true' 
