name: ASP.NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Install EF Tool
        run: |
            dotnet new tool-manifest
            dotnet tool install dotnet-ef

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Generate scripts
        run: dotnet ef migrations script --output ${{env.DOTNET_ROOT}}/sql/sql-script.sql --idempotent --context ApplicationDbContext

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v1
        with:
          # Name of the Azure SQL Server name, like Fabrikam.database.windows.net.
          server-name: tcp:city-discover-tourist.database.windows.net
          # The connection string, including authentication information, for the Azure SQL Server database.
          connection-string: ${{ secrets.CONNECTION_STRING }}
          # Path to SQL script file to deploy
          sql-file: ${{env.DOTNET_ROOT}}/sql/sql-script.sql
