# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - City

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_fa8b9473bfb1469284d23e267045798f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1912784e3b88435ca7419395f08746f3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fa8b9473bfb1469284d23e267045798f }}/donephit/city-discover-tourist-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'City'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e5115dd360144beea1d90a4a351e66ca }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fa8b9473bfb1469284d23e267045798f }}/donephit/city-discover-tourist-server:${{ github.sha }}'